syntax = "proto3";

package auth.v1;

import "common/v1.proto";

// AuthService provides operations for authentication.
service AuthService {
  // SendOtp sends a one-time password (OTP) to the user based on the provided ID and type.
  rpc SendOtp(SendOtpRequest) returns (SendOtpResponse);
  // VerifyOtp verifies the provided OTP for the user based on the ID and type, and returns access and refresh tokens if successful.
  rpc VerifyOtp(VerifyOtpRequest) returns (VerifyOtpResponse);
  // RefreshToken refreshes the access token using a valid refresh token.
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
  // TelegramInit initializes the Telegram authentication process and returns a URL for the user to complete the authentication.
  rpc TelegramInit(TelegramInitRequest) returns (TelegramInitResponse);
  // TelegramVerify
  rpc TelegramVerify(TelegramVerifyRequest) returns (TelegramVerifyResponse);
}

// SendOtpRequest is the request message for sending an OTP to a user.
message SendOtpRequest {
  string identifier = 1;
  common.v1.ContactType type = 2;
}

// SendOtpResponse is the response message indicating whether the OTP was sent successfully.
message SendOtpResponse {
  bool ok = 1;
}

// VerifyOtpRequest is the request message for verifying a one-time password (OTP).
message VerifyOtpRequest {
  string identifier = 1;
  common.v1.ContactType type = 2;
  string otp = 3;
}

// VerifyOtpResponse is the response message indicating whether the OTP was verified successfully.
message VerifyOtpResponse {
  string access_token = 1;
  string refresh_token = 2;
}

// RefreshTokenRequest is the request message for refreshing an access token.
message RefreshTokenRequest {
  string refresh_token = 1;
}

// RefreshTokenResponse is the response message containing the new access token.
message RefreshTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
}

// TelegramVerifyRequest is the request message for verifying Telegram authentication.
message TelegramInitRequest {}

// TelegramInitResponse is the response message for initializing Telegram authentication.
message TelegramInitResponse {
  string url = 1;
}

// TelegramVerifyRequest is the request message for verifying Telegram authentication.
message TelegramVerifyRequest {
  map<string, string> auth_result = 1;
}

// TelegramVerifyResponse is the response message for verifying Telegram authentication.
message TelegramVerifyResponse {
  oneof result {
    string url = 1;
    string access_token = 2;
    string refresh_token = 3;
  }
}
