syntax = "proto3";

package account.v1;

service AccountService {
  rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
}

message GetProfileRequest {
  string id = 1;
}

message GetProfileResponse {
  string          id                = 1;
  optional string email             = 2;
  optional string phone             = 3;
  optional string phone_verified_at = 4;
  optional string email_verified_at = 5;
  Role            role              = 6;
}

enum Role {
  USER  = 0;
  ADMIN = 1;
}